"""Authentication for Boss Zhipin.

Strategy:
1. Try loading saved credential from ~/.config/boss-cli/credential.json
2. Try extracting cookies from local browsers via browser-cookie3
3. Fallback: QR code login in terminal
"""

from __future__ import annotations

import glob
import hashlib
import json
import logging
import os
import platform
import shutil
import subprocess
import sys
import tempfile
import time
from typing import Any

import httpx
import qrcode

from boss_cli.constants import (
    AUTH_HEALTH_CACHE_TTL_S,
    BASE_URL,
    CONFIG_DIR,
    CREDENTIAL_FILE,
    HEADERS,
    REQUIRED_COOKIES,
    QR_CODE_URL,
    QR_DISPATCHER_URL,
    QR_RANDKEY_URL,
    QR_SCAN_LOGIN_URL,
    QR_SCAN_URL,
)

logger = logging.getLogger(__name__)

# Credential TTL: warn and attempt refresh after 7 days
CREDENTIAL_TTL_DAYS = 7
_CREDENTIAL_TTL_SECONDS = CREDENTIAL_TTL_DAYS * 86400

# QR poll config
POLL_TIMEOUT_S = 240  # 4 minutes
_AUTH_HEALTH_CACHE: dict[str, tuple[float, dict[str, Any]]] = {}


# ── Credential data class ───────────────────────────────────────────

class Credential:
    """Holds Boss Zhipin session cookies."""

    def __init__(self, cookies: dict[str, str]):
        self.cookies = cookies

    @property
    def is_valid(self) -> bool:
        return bool(self.cookies)

    @property
    def missing_required_cookies(self) -> list[str]:
        return sorted(REQUIRED_COOKIES - set(self.cookies))

    @property
    def has_required_cookies(self) -> bool:
        return not self.missing_required_cookies

    def to_dict(self) -> dict[str, Any]:
        return {"cookies": self.cookies, "saved_at": time.time()}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Credential:
        return cls(cookies=data.get("cookies", {}))

    def as_cookie_header(self) -> str:
        return "; ".join(f"{k}={v}" for k, v in self.cookies.items())


# ── Credential persistence ──────────────────────────────────────────

def save_credential(credential: Credential) -> None:
    """Save credential to config file."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    CREDENTIAL_FILE.write_text(json.dumps(credential.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")
    CREDENTIAL_FILE.chmod(0o600)
    logger.info("Credential saved to %s", CREDENTIAL_FILE)


def load_credential() -> Credential | None:
    """Load credential from saved file with TTL-based auto-refresh.

    If saved cookies are older than 7 days, automatically attempt to
    refresh from the browser before falling back to stale cookies.
    """
    if not CREDENTIAL_FILE.exists():
        return None
    try:
        data = json.loads(CREDENTIAL_FILE.read_text(encoding="utf-8"))
        cred = Credential.from_dict(data)
        if not cred.is_valid:
            return None
        if not cred.has_required_cookies:
            missing = cred.missing_required_cookies
            # __zp_stoken__ is generated by client-side JS and cannot be
            # obtained via QR login.  Don't reject an otherwise valid
            # credential just because this one cookie is absent.
            if missing != ["__zp_stoken__"]:
                logger.warning(
                    "Saved credential missing required cookies: %s",
                    ", ".join(missing),
                )
                clear_credential()
                return None
            logger.debug("Credential missing __zp_stoken__ (JS-generated), continuing")

        # Check TTL — auto-refresh if stale
        saved_at = data.get("saved_at", 0)
        if saved_at and (time.time() - saved_at) > _CREDENTIAL_TTL_SECONDS:
            logger.info(
                "Credential older than %d days, attempting browser refresh",
                CREDENTIAL_TTL_DAYS,
            )
            fresh, _ = extract_browser_credential()
            if fresh:
                logger.info("Auto-refreshed credential from browser")
                return fresh
            logger.warning(
                "Cookie refresh failed; using existing cookies (age: %d+ days)",
                CREDENTIAL_TTL_DAYS,
            )
        return cred
    except (json.JSONDecodeError, KeyError) as e:
        logger.warning("Failed to load saved credential: %s", e)
    return None


def clear_credential() -> None:
    """Remove saved credential file."""
    if CREDENTIAL_FILE.exists():
        CREDENTIAL_FILE.unlink()
        logger.info("Credential removed: %s", CREDENTIAL_FILE)
    _AUTH_HEALTH_CACHE.clear()


# ── Keychain / environment diagnostics ──────────────────────────────

_KEYCHAIN_ERROR_KEYWORDS = (
    "key for cookie decryption",
    "safe storage",
    "keychain",
    "secretstorage",
    "dpapi",
    "cryptunprotectdata",
    "win32crypt",
)


def _diagnose_extraction_issues(diagnostics: list[str]) -> str | None:
    """Analyse extraction diagnostics for platform-specific issues.

    Returns a user-friendly hint string, or None.
    """
    lowered = " ".join(diagnostics).lower()
    if not any(kw in lowered for kw in _KEYCHAIN_ERROR_KEYWORDS):
        return None

    is_ssh = bool(os.environ.get("SSH_CLIENT") or os.environ.get("SSH_TTY") or os.environ.get("SSH_CONNECTION"))

    if sys.platform == "darwin":
        if is_ssh:
            return (
                "macOS Keychain is locked (SSH session detected).\n"
                "  Fix: security unlock-keychain ~/Library/Keychains/login.keychain-db\n"
                "  Then retry the command."
            )
        return (
            "macOS Keychain permission denied — your terminal is not authorized to read browser cookie encryption keys.\n"
            "  Fix: Open Keychain Access → search for \"<Browser> Safe Storage\" → Access Control → add your Terminal app.\n"
            "  Or click \"Always Allow\" when the Keychain authorization popup appears."
        )
    if sys.platform == "win32":
        return (
            "Windows DPAPI cookie decryption failed.\n"
            "  Possible causes:\n"
            "  1. Chrome is running (locks the cookie database). Try closing Chrome first.\n"
            "  2. browser_cookie3 may not support the latest Chrome cookie encryption format.\n"
            "  3. If Chrome was running, admin privileges may be required for VSS shadowcopy.\n"
            "  Workaround: Set BOSS_COOKIES environment variable manually (see boss login --help)."
        )
    # Linux: gnome-keyring / SecretStorage issues
    return (
        "System keyring access failed — the cookie encryption key could not be retrieved.\n"
        "  If running headless or via SSH, ensure your keyring daemon is unlocked."
    )


# ── Environment variable fallback ───────────────────────────────────

def load_from_env() -> Credential | None:
    """Load cookies from BOSS_COOKIES environment variable.

    Format: "key1=val1; key2=val2; ..."
    """
    raw = os.environ.get("BOSS_COOKIES", "").strip()
    if not raw:
        return None
    cookies: dict[str, str] = {}
    for part in raw.split(";"):
        part = part.strip()
        if "=" not in part:
            continue
        k, v = part.split("=", 1)
        k, v = k.strip(), v.strip()
        if k and v:
            cookies[k] = v
    if not cookies:
        logger.debug("BOSS_COOKIES env set but no valid key=value pairs found")
        return None
    cred = Credential(cookies=cookies)
    logger.info("Loaded %d cookies from BOSS_COOKIES environment variable", len(cookies))
    return cred


# ── Browser cookie extraction ───────────────────────────────────────

# Chromium-based browser base directories
_CHROMIUM_BASE_DIRS: dict[str, str] = {
    "chrome": os.path.join("Google", "Chrome"),
    "edge": "Microsoft Edge",
    "brave": os.path.join("BraveSoftware", "Brave-Browser"),
}

# Default browser order for extraction
_DEFAULT_BROWSER_ORDER = ["chrome", "edge", "firefox", "brave"]

# Optional browsers (added if browser_cookie3 supports them)
_OPTIONAL_BROWSERS = [("Arc", "arc"), ("Chromium", "chromium"), ("Vivaldi", "vivaldi"), ("Opera", "opera")]


def _get_browser_order(cookie_source: str | None = None) -> list[str]:
    """Return browser extraction order, optionally prioritizing a specific browser."""
    if cookie_source:
        target = cookie_source.lower()
        return [target] + [b for b in _DEFAULT_BROWSER_ORDER if b != target]
    return _DEFAULT_BROWSER_ORDER


def _iter_chrome_cookie_files(browser_name: str) -> list[str]:
    """Return cookie file paths for all Chrome profiles."""
    base_dir = _CHROMIUM_BASE_DIRS.get(browser_name)
    if base_dir is None:
        return []

    if sys.platform == "darwin":
        root = os.path.join(os.path.expanduser("~"), "Library", "Application Support", base_dir)
    elif sys.platform == "win32":
        if browser_name == "edge":
            root = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Microsoft", "Edge", "User Data")
        else:
            root = os.path.join(os.environ.get("LOCALAPPDATA", ""), base_dir)
    else:
        if browser_name == "edge":
            root = os.path.join(os.path.expanduser("~"), ".config", "microsoft-edge")
        else:
            root = os.path.join(os.path.expanduser("~"), ".config", base_dir)

    if not os.path.isdir(root):
        return []

    paths: list[str] = []
    default_cookies = os.path.join(root, "Default", "Cookies")
    if os.path.exists(default_cookies):
        paths.append(default_cookies)

    profile_dirs = sorted(glob.glob(os.path.join(root, "Profile *")))
    for profile_dir in profile_dirs:
        cookie_file = os.path.join(profile_dir, "Cookies")
        if os.path.exists(cookie_file):
            paths.append(cookie_file)

    return paths


def _extract_cookies_from_jar(jar: Any, source: str = "unknown") -> dict[str, str] | None:
    """Extract zhipin.com cookies from a browser_cookie3 cookie jar."""
    cookies: dict[str, str] = {}
    for cookie in jar:
        domain = cookie.domain or ""
        if "zhipin.com" in domain:
            if cookie.name and cookie.value:
                cookies[cookie.name] = cookie.value
    if cookies:
        logger.debug("Found %d zhipin cookies from %s", len(cookies), source)
        return cookies
    return None


def _extract_in_process(cookie_source: str | None = None) -> tuple[Credential | None, list[str]]:
    """Extract cookies in the main process.

    On macOS, Chrome encrypts cookies using a key stored in the system Keychain.
    Child processes do NOT inherit the parent's Keychain authorization, so
    browser_cookie3 must run in the main process to decrypt cookies.

    Returns (Credential | None, diagnostics_list).
    """
    try:
        import browser_cookie3 as bc3
    except ImportError:
        logger.debug("browser_cookie3 not installed, skipping in-process extraction")
        return None, ["browser-cookie3 not installed"]

    browser_fns: dict[str, Any] = {
        "chrome": bc3.chrome,
        "firefox": bc3.firefox,
        "edge": bc3.edge,
        "brave": bc3.brave,
    }
    # Add optional browsers if supported
    for display_name, attr in _OPTIONAL_BROWSERS:
        fn = getattr(bc3, attr, None)
        if fn:
            browser_fns[attr] = fn

    diagnostics: list[str] = []
    attempts: list[str] = []

    for name in _get_browser_order(cookie_source):
        fn = browser_fns.get(name)
        if fn is None:
            continue

        if name in _CHROMIUM_BASE_DIRS:
            # Chromium-based: iterate all profiles
            cookie_files = _iter_chrome_cookie_files(name)
            if not cookie_files:
                # No profile dirs found — try the default (no cookie_file arg)
                try:
                    jar = fn(domain_name=".zhipin.com")
                except Exception as e:
                    logger.debug("%s in-process extraction failed: %s", name, e)
                    attempts.append(f"{name}={type(e).__name__}")
                    diagnostics.append(f"{name}: {e}")
                    continue
                cookies = _extract_cookies_from_jar(jar, source=f"{name}(in-process)")
                if cookies:
                    cred = Credential(cookies=cookies)
                    logger.info("Found cookies in %s (in-process, default)", name)
                    return cred, diagnostics
                attempts.append(f"{name}=no-cookies")
                continue

            for cookie_file in cookie_files:
                profile_name = os.path.basename(os.path.dirname(cookie_file))
                try:
                    jar = fn(cookie_file=cookie_file, domain_name=".zhipin.com")
                except Exception as e:
                    logger.debug("%s[%s] in-process extraction failed: %s", name, profile_name, e)
                    attempts.append(f"{name}[{profile_name}]={type(e).__name__}")
                    diagnostics.append(f"{name}[{profile_name}]: {e}")
                    continue
                cookies = _extract_cookies_from_jar(jar, source=f"{name}[{profile_name}](in-process)")
                if cookies:
                    cred = Credential(cookies=cookies)
                    logger.info("Found cookies in %s profile '%s' (in-process)", name, profile_name)
                    return cred, diagnostics
                attempts.append(f"{name}[{profile_name}]=no-cookies")
        else:
            # Non-Chromium (Firefox): use default behavior
            try:
                jar = fn(domain_name=".zhipin.com")
            except Exception as e:
                logger.debug("%s in-process extraction failed: %s", name, e)
                attempts.append(f"{name}={type(e).__name__}")
                diagnostics.append(f"{name}: {e}")
                continue
            cookies = _extract_cookies_from_jar(jar, source=f"{name}(in-process)")
            if cookies:
                cred = Credential(cookies=cookies)
                logger.info("Found cookies in %s (in-process)", name)
                return cred, diagnostics
            attempts.append(f"{name}=no-cookies")

    if attempts:
        logger.debug("In-process extraction attempts: %s", ", ".join(attempts))
    return None, diagnostics


def _extract_via_subprocess(cookie_source: str | None = None) -> tuple[Credential | None, list[str]]:
    """Extract cookies via subprocess (fallback if in-process fails, e.g. SQLite lock).

    Returns (Credential | None, diagnostics_list).
    """
    extract_script = '''
import glob, json, os, sys
try:
    import browser_cookie3 as bc3
except ImportError:
    print(json.dumps({"error": "not_installed"}))
    sys.exit(0)

target = sys.argv[1] if len(sys.argv) > 1 else None

CHROMIUM_BASE_DIRS = {
    "chrome": os.path.join("Google", "Chrome"),
    "edge": "Microsoft Edge",
    "brave": os.path.join("BraveSoftware", "Brave-Browser"),
}

def iter_cookie_files(browser_name):
    base_dir = CHROMIUM_BASE_DIRS.get(browser_name)
    if base_dir is None:
        return []
    if sys.platform == "darwin":
        root = os.path.join(os.path.expanduser("~"), "Library", "Application Support", base_dir)
    elif sys.platform == "win32":
        if browser_name == "edge":
            root = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Microsoft", "Edge", "User Data")
        else:
            root = os.path.join(os.environ.get("LOCALAPPDATA", ""), base_dir)
    else:
        if browser_name == "edge":
            root = os.path.join(os.path.expanduser("~"), ".config", "microsoft-edge")
        else:
            root = os.path.join(os.path.expanduser("~"), ".config", base_dir)
    if not os.path.isdir(root):
        return []
    paths = []
    d = os.path.join(root, "Default", "Cookies")
    if os.path.exists(d):
        paths.append(d)
    for pd in sorted(glob.glob(os.path.join(root, "Profile *"))):
        cf = os.path.join(pd, "Cookies")
        if os.path.exists(cf):
            paths.append(cf)
    return paths

browsers = [
    ("chrome", bc3.chrome),
    ("firefox", bc3.firefox),
    ("edge", bc3.edge),
    ("brave", bc3.brave),
]
for name, attr in [("arc", "arc"), ("chromium", "chromium"), ("vivaldi", "vivaldi"), ("opera", "opera")]:
    fn = getattr(bc3, attr, None)
    if fn:
        browsers.append((name, fn))

if target:
    target_lower = target.lower()
    browsers = [(n, fn) for n, fn in browsers if n.lower() == target_lower]
    if not browsers:
        print(json.dumps({"error": f"unsupported_browser: {target}"}))
        sys.exit(0)

attempts = []
for name, loader in browsers:
    if name in CHROMIUM_BASE_DIRS:
        cookie_files = iter_cookie_files(name)
        if not cookie_files:
            try:
                cj = loader(domain_name=".zhipin.com")
                cookies = {c.name: c.value for c in cj if "zhipin.com" in (c.domain or "")}
                if cookies:
                    print(json.dumps({"browser": name, "cookies": cookies}))
                    sys.exit(0)
                attempts.append(f"{name}=no-cookies")
            except Exception as exc:
                attempts.append(f"{name}={type(exc).__name__}: {exc}")
            continue
        for cf in cookie_files:
            pname = os.path.basename(os.path.dirname(cf))
            try:
                cj = loader(cookie_file=cf, domain_name=".zhipin.com")
                cookies = {c.name: c.value for c in cj if "zhipin.com" in (c.domain or "")}
                if cookies:
                    print(json.dumps({"browser": name, "cookies": cookies}))
                    sys.exit(0)
                attempts.append(f"{name}[{pname}]=no-cookies")
            except Exception as exc:
                attempts.append(f"{name}[{pname}]={type(exc).__name__}: {exc}")
    else:
        try:
            cj = loader(domain_name=".zhipin.com")
            cookies = {c.name: c.value for c in cj if "zhipin.com" in (c.domain or "")}
            if cookies:
                print(json.dumps({"browser": name, "cookies": cookies}))
                sys.exit(0)
            attempts.append(f"{name}=no-cookies")
        except Exception as exc:
            attempts.append(f"{name}={type(exc).__name__}: {exc}")

print(json.dumps({"error": "no_cookies", "attempts": attempts}))
'''

    diagnostics: list[str] = []
    try:
        cmd = [sys.executable, "-c", extract_script]
        if cookie_source:
            cmd.append(cookie_source)

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=15,
        )

        if result.returncode != 0:
            logger.debug("Cookie extraction subprocess failed: %s", result.stderr)
            return None, diagnostics

        output = result.stdout.strip()
        if not output:
            return None, diagnostics

        data = json.loads(output)
        if "error" in data:
            attempts = data.get("attempts") or []
            if attempts:
                logger.debug("Subprocess extraction attempts: %s", ", ".join(str(a) for a in attempts))
                diagnostics.extend(str(a) for a in attempts)
            if data["error"] == "not_installed":
                logger.debug("browser-cookie3 not installed, skipping")
            else:
                logger.debug("No valid Boss Zhipin cookies found: %s", data["error"])
            return None, diagnostics

        cookies = data["cookies"]
        browser_name = data["browser"]
        cred = Credential(cookies=cookies)
        logger.info("Found cookies in %s (subprocess, %d cookies)", browser_name, len(cookies))
        return cred, diagnostics

    except subprocess.TimeoutExpired:
        logger.warning("Cookie extraction timed out (browser may be running)")
        diagnostics.append("subprocess: timed out")
        return None, diagnostics
    except (json.JSONDecodeError, KeyError) as e:
        logger.warning("Cookie extraction parse error: %s", e)
        return None, diagnostics


def extract_browser_credential(cookie_source: str | None = None) -> tuple[Credential | None, list[str]]:
    """Extract Boss Zhipin cookies from local browsers.

    Strategy:
    1. Try in-process first (required on macOS for Keychain access)
    2. Fall back to subprocess (handles SQLite lock when browser is running)

    Args:
        cookie_source: Optional browser name to extract from (e.g., 'chrome', 'firefox').
                       If None, tries all supported browsers in order.

    Returns:
        (Credential | None, diagnostics_list)
    """
    all_diagnostics: list[str] = []

    # 1. In-process (works on macOS, may fail with SQLite lock)
    cred, diag = _extract_in_process(cookie_source)
    all_diagnostics.extend(diag)
    if cred:
        if not cred.has_required_cookies:
            logger.warning(
                "In-process cookies missing required keys: %s",
                ", ".join(cred.missing_required_cookies),
            )
        else:
            save_credential(cred)
            return cred, all_diagnostics

    # 2. Subprocess fallback (handles SQLite lock, but fails on macOS Keychain)
    logger.debug("In-process extraction failed, trying subprocess fallback")
    cred, diag = _extract_via_subprocess(cookie_source)
    all_diagnostics.extend(diag)
    if cred:
        if not cred.has_required_cookies:
            logger.warning(
                "Subprocess cookies missing required keys: %s",
                ", ".join(cred.missing_required_cookies),
            )
        else:
            save_credential(cred)
            return cred, all_diagnostics

    if not cred:
        logger.warning("Cookie extraction failed in both in-process and subprocess modes")
    return None, all_diagnostics


# ── QR Code terminal rendering ──────────────────────────────────────

def _render_qr_half_blocks(matrix: list[list[bool]]) -> str:
    """Render QR matrix using Unicode half-block characters (▀▄█ and space).

    Same approach as xiaohongshu-cli: two rows are combined into one
    terminal line using half-block glyphs, halving the vertical space.
    """
    if not matrix:
        return ""

    # Add 1-module quiet zone
    size = len(matrix)
    padded = [[False] * (size + 2)]
    for row in matrix:
        padded.append([False] + list(row) + [False])
    padded.append([False] * (size + 2))
    matrix = padded
    rows = len(matrix)

    # Check terminal width
    term_cols = shutil.get_terminal_size(fallback=(80, 24)).columns
    qr_width = len(matrix[0])
    if qr_width > term_cols:
        logger.warning("Terminal too narrow (%d) for QR (%d)", term_cols, qr_width)
        return ""

    lines: list[str] = []
    for y in range(0, rows, 2):
        line = ""
        top_row = matrix[y]
        bottom_row = matrix[y + 1] if y + 1 < rows else [False] * len(top_row)
        for x in range(len(top_row)):
            top = top_row[x]
            bottom = bottom_row[x]
            if top and bottom:
                line += "█"
            elif top and not bottom:
                line += "▀"
            elif not top and bottom:
                line += "▄"
            else:
                line += " "
        lines.append(line)
    return "\n".join(lines)


def _display_qr_in_terminal(data: str) -> bool:
    """Display *data* as a QR code in the terminal using Unicode half-blocks.

    Returns True on success.
    """
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_L)
    qr.add_data(data)
    qr.make(fit=True)
    modules = qr.get_matrix()

    rendered = _render_qr_half_blocks(modules)
    if rendered:
        print(rendered)
        return True

    # Fallback to basic ASCII
    qr2 = qrcode.QRCode(
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=1,
        border=1,
    )
    qr2.add_data(data)
    qr2.make(fit=True)
    qr2.print_ascii(invert=True)
    return True


def _open_image_file(path: str) -> None:
    """Open an image file with the system default viewer."""
    system = platform.system()
    try:
        if system == "Darwin":
            subprocess.Popen(["open", path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        elif system == "Windows":
            os.startfile(path)  # type: ignore[attr-defined]
        else:
            subprocess.Popen(["xdg-open", path], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except OSError as exc:
        logger.debug("Failed to open QR image: %s", exc)


async def _fetch_and_display_qr(client: httpx.AsyncClient, qr_id: str) -> None:
    """Fetch the QR code image from Boss API and display it.

    The server-generated QR image contains the correct scannable content
    that the Boss Zhipin APP can recognise. We save it to a temp file and
    open it with the system image viewer, plus render it in the terminal
    as a fallback.
    """
    # Fetch QR image from API
    resp = await client.get(QR_CODE_URL, params={"content": qr_id})
    resp.raise_for_status()

    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(suffix=".png", prefix="boss_qr_", delete=False)
    tmp.write(resp.content)
    tmp.close()
    logger.debug("QR image saved to %s", tmp.name)

    # Try to open with system viewer
    _open_image_file(tmp.name)
    print(f"  📁 二维码图片已保存到: {tmp.name}")

    # Also try terminal rendering — decode the image to find the encoded content
    try:
        from PIL import Image
        from pyzbar.pyzbar import decode as zbar_decode

        img = Image.open(tmp.name)
        decoded = zbar_decode(img)
        if decoded:
            qr_content = decoded[0].data.decode("utf-8")
            logger.debug("Decoded QR content: %s", qr_content)
            _display_qr_in_terminal(qr_content)
    except ImportError:
        # pyzbar / Pillow not installed — terminal QR not available, image viewer is enough
        logger.debug("pyzbar/Pillow not installed, skipping terminal QR rendering")
    except Exception as exc:
        logger.debug("Failed to decode QR image for terminal display: %s", exc)


# ── QR Login flow ───────────────────────────────────────────────────

async def _get_qr_session(client: httpx.AsyncClient) -> dict[str, str]:
    """Step 1: Get QR session (qrId, randKey, secretKey)."""
    resp = await client.post(QR_RANDKEY_URL)
    resp.raise_for_status()
    data = resp.json()
    if data.get("code") != 0:
        raise RuntimeError(f"Failed to get QR session: {data.get('message', 'Unknown error')}")
    return data["zpData"]


async def _wait_for_scan(client: httpx.AsyncClient, qr_id: str) -> bool:
    """Step 3: Long-poll waiting for QR scan."""
    try:
        resp = await client.get(QR_SCAN_URL, params={"uuid": qr_id}, timeout=35)
        resp.raise_for_status()
        data = resp.json()
        return data.get("scaned", False)
    except httpx.ReadTimeout:
        return False


async def _wait_for_confirm(client: httpx.AsyncClient, qr_id: str) -> bool:
    """Step 4: Long-poll waiting for login confirmation.

    Must check the ``login`` field in the JSON body — a 200 status alone
    does NOT mean the user has confirmed on their phone.
    """
    try:
        resp = await client.get(QR_SCAN_LOGIN_URL, params={"qrId": qr_id}, timeout=35)
        resp.raise_for_status()
        data = resp.json()
        return data.get("login", False) is True
    except httpx.ReadTimeout:
        return False


async def _dispatch_login(client: httpx.AsyncClient, qr_id: str) -> Credential:
    """Step 5: Get final login cookies via dispatcher."""
    resp = await client.get(
        QR_DISPATCHER_URL,
        params={"qrId": qr_id, "pk": "header-login"},
    )
    resp.raise_for_status()

    # Extract cookies from response
    cookies = {}
    for name, value in resp.cookies.items():
        cookies[name] = value

    # Also grab cookies accumulated on the client
    for name, value in client.cookies.items():
        cookies[name] = value

    # QR dispatcher can complete before the web session is fully hydrated.
    # Visit the site once to collect any additional auth cookies such as __zp_stoken__.
    try:
        warmup = await client.get("/", timeout=15)
        warmup.raise_for_status()
        for name, value in warmup.cookies.items():
            cookies[name] = value
        for name, value in client.cookies.items():
            cookies[name] = value
    except httpx.HTTPError as exc:
        logger.debug("QR warmup request failed: %s", exc)

    if not cookies:
        raise RuntimeError("Login dispatcher returned no cookies")

    credential = Credential(cookies=cookies)

    # __zp_stoken__ is generated by client-side JavaScript and cannot be
    # obtained via the QR HTTP flow.  Do NOT try to supplement it from
    # browser cookies — the browser's stoken is tied to its own session
    # and will always mismatch the fresh QR session's wt2/wbg/zp_at.
    if not credential.has_required_cookies:
        missing = credential.missing_required_cookies
        if missing == ["__zp_stoken__"]:
            logger.warning(
                "QR login obtained session cookies but __zp_stoken__ is "
                "unavailable (generated by JS). Some APIs may return code=37. "
                "Re-run `boss login` from a browser session to fix."
            )
        else:
            raise RuntimeError(
                "二维码登录未拿到完整的 Web 登录态，缺少关键 Cookie: "
                f"{', '.join(missing)}。请先在浏览器完成登录后重新运行 boss login。"
            )

    return credential


async def qr_login() -> Credential:
    """Full QR code login flow.

    1. Get QR session
    2. Display QR code in terminal (Unicode half-blocks)
    3. Wait for scan (long-polling)
    4. Wait for confirm (long-polling)
    5. Dispatch to get cookies
    """
    async with httpx.AsyncClient(
        base_url=BASE_URL,
        headers=HEADERS,
        follow_redirects=True,
        timeout=httpx.Timeout(30, read=40),
    ) as client:
        # Step 1: Get QR session
        session = await _get_qr_session(client)
        qr_id = session["qrId"]

        # Step 2: Fetch QR image from API and display
        print("\n📱 请使用 Boss 直聘 APP 扫描以下二维码登录:\n")
        await _fetch_and_display_qr(client, qr_id)
        print("\n⏳ 扫码后请在手机上确认登录...")
        print(f"   (QR ID: {qr_id[:20]}...)\n")

        # Step 3: Wait for scan
        max_retries = 6  # ~3 min with 30s timeout each
        scanned = False
        for _ in range(max_retries):
            scanned = await _wait_for_scan(client, qr_id)
            if scanned:
                print("  📲 已扫码，请在手机上确认...")
                break

        if not scanned:
            raise RuntimeError("二维码已过期，请重试 (boss login)")

        # Step 4: Wait for confirm
        confirmed = False
        for _ in range(max_retries):
            confirmed = await _wait_for_confirm(client, qr_id)
            if confirmed:
                break

        if not confirmed:
            raise RuntimeError("确认超时，请重试 (boss login)")

        # Step 5: Dispatch
        credential = await _dispatch_login(client, qr_id)
        save_credential(credential)
        print("\n✅ 登录成功！凭证已保存到", CREDENTIAL_FILE)
        return credential


# ── Unified get_credential ──────────────────────────────────────────

def get_credential() -> Credential | None:
    """Try all auth methods and return credential.

    1. Saved credential file
    2. Environment variable (BOSS_COOKIES)
    3. Browser cookie extraction
    """
    cred = load_credential()
    if cred:
        logger.info("Loaded credential from %s", CREDENTIAL_FILE)
        return cred

    cred = load_from_env()
    if cred:
        logger.info("Loaded credential from BOSS_COOKIES env")
        save_credential(cred)
        return cred

    cred, _ = extract_browser_credential()
    if cred:
        logger.info("Extracted credential from browser")
        return cred

    return None


def _credential_cache_key(credential: Credential) -> str:
    payload = json.dumps(sorted(credential.cookies.items()), ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def verify_credential_details(credential: Credential, *, force_refresh: bool = False) -> dict[str, Any]:
    """Verify credential health across the key authenticated flows."""
    if not credential.has_required_cookies:
        missing = ", ".join(credential.missing_required_cookies)
        return {
            "authenticated": False,
            "search_authenticated": False,
            "recommend_authenticated": False,
            "reason": f"缺少关键 Cookie: {missing}",
        }

    from .client import BossClient
    from .exceptions import BossApiError, SessionExpiredError

    cache_key = _credential_cache_key(credential)
    now = time.time()
    if not force_refresh:
        cached = _AUTH_HEALTH_CACHE.get(cache_key)
        if cached and (now - cached[0]) <= AUTH_HEALTH_CACHE_TTL_S:
            return dict(cached[1])

    checks = {
        "search_authenticated": False,
        "recommend_authenticated": False,
    }
    failures: list[str] = []

    with BossClient(credential, request_delay=0.2) as client:
        try:
            client.search_jobs(query="Python", city="100010000", page=1, page_size=1)
            checks["search_authenticated"] = True
        except SessionExpiredError as exc:
            failures.append(f"search: {exc}")
        except BossApiError as exc:
            failures.append(f"search: 登录态校验失败: {exc}")

        try:
            client.get_recommend_jobs(page=1)
            checks["recommend_authenticated"] = True
        except SessionExpiredError as exc:
            failures.append(f"recommend: {exc}")
        except BossApiError as exc:
            failures.append(f"recommend: 登录态校验失败: {exc}")

    authenticated = checks["search_authenticated"]
    result: dict[str, Any] = {
        "authenticated": authenticated,
        **checks,
    }
    if failures:
        result["reason"] = "; ".join(failures)
    _AUTH_HEALTH_CACHE[cache_key] = (time.time(), dict(result))
    return result


def verify_credential(credential: Credential, *, force_refresh: bool = False) -> tuple[bool, str | None]:
    """Verify that the credential can access an authenticated API."""
    result = verify_credential_details(credential, force_refresh=force_refresh)
    return result["authenticated"], result.get("reason")
